package com.softserveinc.training;

// Generated by Selenium IDE

import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.open;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;

public class RozetkaSelenide {
    @Test
    public void robotxiaomi() {
        String userName = "user" + System.currentTimeMillis();
        
        open("https://rozetka.com.ua/");
        $(By.linkText("войдите в личный кабинет")).click();
        $(By.linkText("Зарегистрироваться")).click();
        $(By.name("title")).sendKeys(userName);
        $(By.name("login")).sendKeys(userName + "@gmail.com");
        $(By.name("password")).sendKeys("P@ssw0rd");
        $(By.cssSelector(".btn-link-sign > .btn-link-i")).click();
        $(By.linkText(userName)).shouldBe(visible);
        $(By.name("text")).click();
        $(By.name("text")).sendKeys("робот пылесос xiaomi");
        $(By.name("text")).sendKeys(Keys.ENTER);
        assertThat($(By.cssSelector(".g-i-tile:nth-child(2) .g-i-tile-i-title")).shouldBe(visible).getText(), is("Робот-пылесос Xiaomi RoboRock Sweep One Vacuum Cleaner s50 White (S502-00) (Международная версия)"));
        assertThat($(By.cssSelector("#goods_price_block_45433456 .g-price-old-uah span")).getText(), is("13 799"));
        $(By.linkText(userName)).hover();
        $(By.linkText("Выход")).shouldBe(visible).click();
    }
}

